### ISSUE TITLE
ng-demo doesn't contains the demo

### ISSUE THREAD

**Issue by ljcp** [triniwiz/nativescript-webrtc#11]
the https://github.com/triniwiz/nativescript-webrtc/tree/master/demo-ng doesn't not contain the angular demo , it's just the plain nativescript default demo app

**Comment by triniwiz** [comment]
Weird it does contain the angular demo 🤔

**Comment by ljcp** [comment]
thank you for your fast response , well if you go to https://github.com/triniwiz/nativescript-webrtc/blob/master/demo-ng/app/call.service.ts , it doesn't exist in master , should I use v2 branch ? can you tell me the difference between master and v2 ?

**Comment by triniwiz** [comment]
Yes you can check out v2 I was upgrading the branch and forgot to move it 😕

**Comment by ljcp** [comment]
thank you , amazing work you have done with so many plugins ! , I will start using this one a lot.
