### ISSUE TITLE
Video tag WebRTCView  aspect ratio

### ISSUE THREAD

**Issue by ljcp** [triniwiz/nativescript-webrtc#12]
Hi there ,

it's posible to use stretch or object-fit with 

`<WebRTCView></WebRTCView>`

 to conserve the aspect ratio of the video ? 

thanks a lot.

**Comment by triniwiz** [comment]
Atm no but I can look at adding it

**Comment by triniwiz** [comment]
Now you can use `scaling="fit"` or `scaling="fill"` or `scaling="none"`

**Comment by ljcp** [comment]
oh wow ! you are fast , thank you so much !

**Comment by rkeller1** [comment]
@ljcp have you tried this ? 
i don't get it working and on ios my picture is stretched
