### ISSUE TITLE
Video is stretched on iOS

### ISSUE THREAD

**Issue by rkeller1** [triniwiz/nativescript-webrtc#18]
Currently I'm facing an issue just on iOS with Typescript.
When using the webrtcview on iOS the video image is stretched over the screen so the aspect ratio is changed and image looks a bit strange.

On Android everything looks good.

I tried the new scaling attribute inside the component layout on webRTCView tag but nothing changed.

On Android it looks even good without setting the parameter.

On iOS no change worked wether the scaling attribute nor changing the video resolution.

Is it a bug or do I missing something ?

**Comment by codingcronus** [comment]
+1
I have encountered the same issue.
