### ISSUE TITLE
when Mobile WebRTC is called from Web WebRTC

### ISSUE THREAD

**Issue by ukik** [triniwiz/nativescript-webrtc#23]
System.err: java.lang.NullPointerException
System.err:     at org.webrtc.JniHelper.getStringBytes(JniHelper.java:25)
System.err:     at org.webrtc.PeerConnection.nativeAddIceCandidate(Native Method)
System.err:     at org.webrtc.PeerConnection.addIceCandidate(PeerConnection.java:868)
System.err:     at co.fitcom.fancywebrtc.FancyRTCPeerConnection.lambda$addIceCandidate$2(FancyRTCPeerConnection.java:340)
System.err:     at co.fitcom.fancywebrtc.-$$Lambda$FancyRTCPeerConnection$xWAf_76mA1pZy3hDK6RyZSpp1wc.run(lambda)
System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
System.err:     at java.lang.Thread.run(Thread.java:841)
ActivityManager: Process com.github.triniwiz.nativescript.webrtc.demo.vue (pid 25655) has died.

**Comment by codingcronus** [comment]
You should probably list your source code for emitting the ICE candidate via your signaling service. Maybe your request object is not valid.

**Comment by ukik** [comment]
this is my experiment: https://github.com/ukik/nativescript-webrtc

unfortunately, i cannot communicate between mobile n web

**Comment by triniwiz** [comment]
Any errors ?

**Comment by ukik** [comment]
yes, transfer IceCandidate failed on mobile side
