### ISSUE TITLE
App  crash on starting video call

### ISSUE THREAD

**Issue by nkemerchou** [triniwiz/nativescript-webrtc#27]
### If the demo apps cannot help and there is no issue for your problem, tell us about it
Please, ensure your title is less than 63 characters long and starts with a capital
letter.

### Which platform(s) does your issue occur on?
- iOS/Android/Both 
- iOS/Android versions 
- emulator or device. What type of device?

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/tns-core-modules/package.json` file in your project)
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)

### Please, tell us how to recreate the issue in as much detail as possible. 
Describe the steps to reproduce it.

### Is there any code involved? 
 - provide a code example to recreate the problem 
 - (EVEN BETTER) provide a .zip with application or refer to a repository with application where the problem is reproducible.

**Comment by nkemerchou** [comment]
Can you please advise on what could be the reason to the application crash, i just did a tns project (angular) and everything work until i click on the user to start the camera - the weird thing is tat it work with your demo-ng project but not with the project i did, even thought every thing is the same not sure what is missing---- please advise!!!

**Comment by triniwiz** [comment]
What version of {N}?

**Comment by abahrisd** [comment]
Face with same problem - sometimes app freeze on answer videocall. No errors in console, just freeze. What could be problem?

**Comment by Macarthurval** [comment]
Same here

**Comment by Macarthurval** [comment]
For me the error only happens in Android, exactly at `this.webrtc.makeOffer(new org.webrtc.MediaConstraints()); `, so I think that the problem is really in fancy-webrtc-android.

**Comment by triniwiz** [comment]
@Macarthurval that's the error ?

**Comment by triniwiz** [comment]
Also something tells me you might  be using the older api

**Comment by triniwiz** [comment]
Please try again in `.19`

**Comment by Macarthurval** [comment]
I've just tried with `"nativescript-webrtc-plugin": "^2.0.0-alpha.19"` and the result was exactly the same.
