### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by dragonfly-d** [triniwiz/nativescript-webrtc#28]
The issue occurs on ios emulator (ios device not tested) but on android device it runs well.
- tns version: 6.1.2
- Plugin version: ^2.0.0-alpha.19

### steps to reproduce:
add tns plugin to project: tns plugin add nativescript-webrtc-plugin
run ios app: tns run ios

### build failed message:
Command CompileSwift failed with a nonzero exit code

note: Using new build systemnote: Planning buildnote: Constructing build descriptionwarning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the socketSample editor. (in target 'socketSample' from project 'socketSample')
***BUILD FAILED***

**Comment by Cateye82** [comment]
I have the same issue, you closed it on the same day. Did you find a solution?
TNS Version: 6.2.0
Plugin Version: ^2.0.0-alpha.19
