### ISSUE TITLE
No static method create()Lorg/webrtc/EglBase

### ISSUE THREAD

**Issue by thecicada** [triniwiz/nativescript-webrtc#31]
I've cloned the demo and followed the instruction giving, everything went smooth except when I ran the app I see error "No static method create()Lorg/webrtc/EglBase", The terminal doesn't seem to show any error during the build proccess.

Any idea?

```
An uncaught Exception occurred on "pool-1-thread-1" thread.
No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/org.nativescript.demo-reFO0wWo-ZH_Y6Ly00JbLw==/base.apk!classes2.dex)

StackTrace:
java.lang.NoSuchMethodError: No static method create()Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/org.nativescript.demo-reFO0wWo-ZH_Y6Ly00JbLw==/base.apk!classes2.dex)
	at co.fitcom.fancywebrtc.FancyWebRTCEglUtils.getRootEglBase(FancyWebRTCEglUtils.java:13)
	at co.fitcom.fancywebrtc.FancyWebRTC.lambda$init$0(FancyWebRTC.java:98)
	at co.fitcom.fancywebrtc.-$$Lambda$FancyWebRTC$jFoisGouehK4C4J-BYA5BfOZep4.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

I'm not sure what causes the issue, but I'd really appreciate it if you could help enlighten me on fixing it.

Looking forward to hearing from you

**Comment by hrueger** [comment]
Did you try putting `android.enableDexingArtifactTransform.desugaring=false` in your `App_Ressources/Android/gradle.properties`? That worked for me. Just create the file if it doesn't exist.

**Comment by Jmchemama** [comment]
Hi, i have a same issue. the application crash on the call to the init function.

**Comment by jmclarkson** [comment]
I am getting the same issue.  Is there an estimate of when this might be resolved?

**Comment by ejlocop** [comment]
facing the same issue when running the demo application (both demo and demo-vue)

**Comment by radityasya** [comment]
do you have camera enabled?

**Comment by lehongwang** [comment]
please, fix this bug, i couldnot even run the demo

**Comment by lehongwang** [comment]
> do you have camera enabled?
> I have experienced that issue before
> but I managed to get rid of it

how can you get rid of it ?? please guide me

**Comment by dmitryr117** [comment]
Make sure to set this in **app.gradle** 
`
android {
  defaultConfig {
    minSdkVersion 24
    ...
  }
  ...
}
`
Otherwise the error will persist.

**Comment by triniwiz** [comment]
@dmitryr117 with the latest release things should be fine

**Comment by Argus444** [comment]
> Make sure to set this in **app.gradle**
> `android { defaultConfig { minSdkVersion 24 ... } ... }`
> Otherwise the error will persist.

This worked for me. Thank you!

**Comment by triniwiz** [comment]
Quick question do y’all add the following to your gradle ?
```gradle

compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
  }

```

**Comment by 4RGUS** [comment]
> Quick question did y’all add the following to your gradle ?
> 
> ```groovy-gradle
> compileOptions {
>         sourceCompatibility 1.8
>         targetCompatibility 1.8
>   }
> ```

Yes I did
