### ISSUE TITLE
No angular demo in master branch

### ISSUE THREAD

**Issue by xaosaki** [triniwiz/nativescript-webrtc#33]
Hello, can you add actual example for Angular in to master?

**Comment by Cateye82** [comment]
Hi, I'm a Nativescript-Angular user and facing some issues directly after installing the plugin within the init method of the class.
What I did is:
- Installed the Plugin
- Loaded the Angular version of the module inside the app.module.ts (until that point everything is fine)
- Calling "WebRTC.init();" in the main.ts with "import {WebRTC} from "nativescript-webrtc-plugin";"

This causes an error "no static method create() in class Lorg/webrtc/EglBase;"

Is it possible for you to just write the usual way how to set it up correctly?
Unfortunately I didn't found any other example or solution (git repo).

Many thanks.

**Comment by roblav96** [comment]
@triniwiz

Not sure if this was intentional, but the latest `ng` demo's were [merged](https://github.com/triniwiz/nativescript-webrtc/pull/40) into [`triniwiz:alpha22`](https://github.com/triniwiz/nativescript-webrtc/tree/alpha22) branch 😇

**Comment by triniwiz** [comment]
@roblav96 correct so ill merge into master later
