### ISSUE TITLE
 I connect the audio on the web with calling from mobile

### ISSUE THREAD

**Issue by walterg20** [triniwiz/nativescript-webrtc#34]
How can I get the audio coupling in the call from the web to the mobile, with the earphone it returns the sound,
It is the version 1.0.2 of the plugin, the new versions stop after asking the permission of camera and audio

**Comment by triniwiz** [comment]
I believe I left it up to the dev to handle how they want to ask for permission, there is `WebRTC.requestPermissions` to help
