### ISSUE TITLE
webRTC.getUserMedia() returns me some weird array

### ISSUE THREAD

**Issue by Argus444** [triniwiz/nativescript-webrtc#43]
**Which platform(s) does your issue occur on?**
- Android

**What type of device?**
- Physical device. 

**Version Numbers:**
- CLI: tns version 6.7.8 
- Cross-platform modules: 6.5.8
- Runtime(s): 
  "tns-android": {
      "version": "6.5.0"
    }
  "tns-ios": {
      "version": "6.5.1"
    }
- Plugin(s): 
{
  "nativescript": {
    "id": "org.nativescript.WebRTCTestApp",
    "tns-android": {
      "version": "6.5.0"
    },
    "tns-ios": {
      "version": "6.5.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "dependencies": {
    "@nativescript/theme": "~2.3.0",
    "nativescript-socketio": "^3.3.1",
    "nativescript-videoplayer": "^4.2.1",
    "nativescript-webrtc-plugin": "^2.0.0-alpha.22",
    "tns-core-modules": "~6.5.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.5.0"
  },
  "gitHead": "20a65d338ae8f8911087ab6615b89363f864b07b",
  "readme": "NativeScript Application"
}

**The problem:**
My front camera pops up which helped me make sure that camera is started. I used webRTC.getUserMedia() to store the incoming mediastream into a variable. But it returns something which I am sure is not not even close to how mediastreams usually are. This is how it looks: **[b5ee0bd9-bde8-4520-b9fd-60b719bf33bb:A=1:V=1]**

**How to reproduce:**
On press of a button I check for WebRTC.hasPermissions(). once it fulfils the hasPermission, I invoke webRTC.getUserMedia()

**code Involved:**
var WebRTC = require('nativescript-webrtc-plugin').WebRTC
WebRTC.init();
const webRTC = new WebRTC({
    enableAudio:true,
    enableVideo:false,
    iceServers : [
        { 'url': 'stun:stun.l.google.com:19302' },
        { 'url': 'xyz', 'username': 'xyz', 'credential': 'xyz' }
    ]
})

onTap(){
if(!WebRTC.hasPermissions()){
            try{
                WebRTC.requestPermissions();
            }catch(e){
                console.log(e)
            }
        }
        let localstream = await webRTC.getUserMedia();
        console.log(localstream)
}

**Comment by triniwiz** [comment]
I need to add a deprecated to that class because the v2 way is the only classes that's being supported so please try the v2 demo located [here](https://github.com/triniwiz/nativescript-webrtc/blob/master/demo/app/standard/)

**Comment by Argus444** [comment]
> I need to add a deprecated to that class because the v2 way is the only classes that's being supported so please try the v2 demo located [here](https://github.com/triniwiz/nativescript-webrtc/blob/master/demo/app/standard/)

Thank You for your quick reply. I tried and used the following code:
public setUpUserMedia() {
        const video = new Map();
        video.set('facingMode', 'user');
        this.cameraPosition = 'user';
        video.set('width', 960);
        video.set('height', 720);
        const constraints = new TNSRTCMediaStreamConstraints(true, video);
        TNSRTCMediaDevices.getUserMedia(constraints)
            .then(mediaStream => {
                this.localStream = mediaStream;
                this.localView.srcObject = mediaStream;
            })
            .catch(error => {
                console.log(error);
            });
    }

I did a console.log for mediaStream. I get the following output:
{
  "_stream": {}
}

Am I missing some thing

**Comment by triniwiz** [comment]
That’s fine it just need to be used by the correct class/methods

**Comment by Argus444** [comment]
> That’s fine it just need to be used by the correct class/methods

Thank you once again, it works flawless
