### ISSUE TITLE
Stop Play video

### ISSUE THREAD

**Issue by Marwen238** [triniwiz/nativescript-webrtc#6]
Hi friends,
i use the demo and i run it , but i have to stop only video, so how i can do that ?
thank you ...

**Comment by triniwiz** [comment]
It's not possible to change the quality w/o stopping the video first

**Comment by Marwen238** [comment]
yeah , i d'ont now how to stop only the video without audio ?

**Comment by triniwiz** [comment]
With the new api u can get the track and disable it
