### ISSUE TITLE
Unable to connect between two different networks

### ISSUE THREAD

**Issue by JijeshP** [triniwiz/nativescript-webrtc#9]
It's working perfectly on same network. when i trying to call from different network it's not working.
i tried using both google stun and stun:numb.viagenie.ca. 

Which platform(s) does your issue occur on?
- iOS/Android/Both

**Comment by triniwiz** [comment]
Test again and LMK

**Comment by triniwiz** [comment]
Tested and works in the latest release

**Comment by rkeller1** [comment]
Can you tel me how to setup the iceServers correctly using the TNSRTCPeerConnection ?
